### ISSUE TITLE
 Generate Search Results

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#10]
Create a search results template. Query the database with any supplied query or zipcode. Display search results

  - [x] Search/filter by region
  - [x] Search/filter by organization
  - [x] Search/filter by activity

Display search results:

  - [x] Image
  - [x] Title
  - [x] Data
  - [x] Description

**Comment by brandonbrown** [comment]
Feedback on #9 is applicable here

**Comment by fsheremetyeva** [comment]
A user will be able to search/filter by region, organization, activity. Search results will be displayed in a grid like template with the image of the organization, the title, the date and a small excerpt of the opportunity. The user than can click on "Learn More" and get additional information.
