### ISSUE TITLE
Initial Dashboard for volunteer account

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#11]
Create a dashboard template. Add ability to change basic information. 

A user is able to add/edit and delete information:

- [x] Add new contact information
- [x] Remove contact information
- [x] Modify contact information
- [x] Volunteer History

Other Features:
- [x] Pie chart summarizing volunteer activity
- [x] Generate Certificate

**Comment by brandonbrown** [comment]
Feedback on #7 can be applied here
