### ISSUE TITLE
Initial Dashboard for Non-profit organizations.

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#12]
As an organization I am able to create and manage volunteer listings:

I can add or update volunteer opportunities:

- [x] Add/Edit Volunteer Opportunity
  - [x] Name
  - [x] Location
  - [x] Date(s)
  - [x] Times
  - [x] Description
  - [x] Images

- [x] Delete Opportunity

**Comment by brandonbrown** [comment]
As a non-profit organization, I can add or update volunteer opportunities:

- [ ] Add/Edit Volunteer Opportunity
  - [ ] Name
  - [ ] Location
  - [ ] Date(s)
  - [ ] Times
  - [ ] Description
  - [ ] Direct Needs
  - [ ] Images
  - [ ] Resources/links

- [ ] Opportunity Status
  - [ ] Draft
  - [ ] Live: Accepting Volunteers
  - [ ] Complete
  - [ ] Cancelled

- [ ] Delete Opportunity

**Comment by fsheremetyeva** [comment]
When an organization saves a new volunteer entry it is automatically goes live. I don't believe saving drafts will be a feature as there is a minimal amount of information they will be submitting. If the opportunity is no longer relevant/available there is a "cancel/delete" option.

**Comment by fsheremetyeva** [comment]
As an organization I am able to create and manage volunteer listings:

As a non-profit organization, I can add or update volunteer opportunities:

- [ ] Add/Edit Volunteer Opportunity
  - [ ] Name
  - [ ] Location
  - [ ] Date(s)
  - [ ] Times
  - [ ] Description
  - [ ] Images

- [ ] Delete Opportunity
