### ISSUE TITLE
Ability to log time spent volunteering

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#13]
As a volunteer I am able to add records of my volunteer work.

- [x] Form to Add
  - [x] Date
  - [x] Organization Name
  - [x] Time spent volunteering
  - [x] Description
- [x] Form to Edit
  - [x] Date
  - [x] Organization Name
  - [x] Time spent volunteering
  - [x] Description
- [x] Form to delete
  - [x] Date
  - [x] Organization Name
  - [x] Time spent volunteering
  - [x] Description

**Comment by brandonbrown** [comment]
As a volunteer, I can claim time spent volunteering.

As a non-profit organization, I can confirm claims of volunteering.

**Comment by fsheremetyeva** [comment]
Thank you. Precisely!
