### ISSUE TITLE
Ability to generate a "certificate" of time spent volunteering

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#14]
Use FPDF Library to generate a certificate with logged volunteer hours and volunteers information.

**Comment by brandonbrown** [comment]
As a non-profit, I can confirm volunteering and offer official certificates for volunteers needs.

As a volunteer, I can print and/or share earned certificates as proof of volunteer work.

**Comment by fsheremetyeva** [comment]
The system will generate certificates upon volunteer's request in good faith based upon their submitted information.
