### ISSUE TITLE
PHP Specialist Instructors

### ISSUE THREAD

**Issue by brandonbrown** [fsheremetyeva/capstone#17]
For any help with PHP development, it would be smart to reach out to:

Rachel Higley:
  - Github: @rhigleyfs (recommend adding Rachel as a collaborator)
  - Discord: rachelhigley#8591

Joe Cavagna:
  - Github: @jcavagna 
  - Slack: jcavagna

**Comment by fsheremetyeva** [comment]
@brandonbrown thank you for your recommendations.
