### ISSUE TITLE
Add instructor as collaborators

### ISSUE THREAD

**Issue by brandonbrown** [fsheremetyeva/capstone#2]
Please add the following github user accounts as collaborators on this project:

brandonbrown
markmichon
reactivepixel
emedialabs
thisisbrad
jerrytk214
jcavagna

**Comment by fsheremetyeva** [comment]
I added all accounts except "emedialabs", it wasn't found on Github

**Comment by brandonbrown** [comment]
In place of emedialabs, please add @eMediaLab

**Comment by fsheremetyeva** [comment]
eMediaLab was added.
