### ISSUE TITLE
Pitch: Target Audience Refinement

### ISSUE THREAD

**Issue by brandonbrown** [fsheremetyeva/capstone#3]
Having the goal of accommodating everyone or a mass audience with your first run of an application is great. That goal, however, should be seen more as a 5 year plan, if not further. The more you can focus your initial target audience, the better you'll understand the strengths and weaknesses of your product.

For instance, would this application be better suited to a large not-for-profit organization, a local church group, or a response oriented event (natural disaster assistance for example)? Having all of these demographics as customers would, of course, be optimal. However, serving one slice of a large demographic well will make your application stronger out of the gate.

Consider adding a set of user stories while you solidify this concept, so you can remind yourself who you are really designing for in those moments you catch yourself designing for the crowd.

**Comment by fsheremetyeva** [comment]
Thank you for your feedback, @brandonbrown. I will revise my plan to targeting high school aged students for an initial target as that seems to have the greatest use and reach -- as it's useful for students applying for college, meeting any volunteer goals for student competitions, and similar purposes.

I think it would also make most sense on the non-profit side to focus on the smaller/local organizations as the larger organizations may already have some sort of internal infrastructure setup for handling volunteer management/scheduling.

Does that sound fine to you? If so I will go ahead then and close this issue. (Assuming for going through the normal workflow of GitHub issue tracking.) Thanks again for the feedback.
