### ISSUE TITLE
Pitch: Concept Clarification

### ISSUE THREAD

**Issue by brandonbrown** [fsheremetyeva/capstone#4]
How many different interfaces or roles will be necessary to fulfill this concept? The organizations and volunteers at minimum need interfaces, but will there also be a "marketing" or informational site that casual visitors can see volunteer needs in their area?

**Comment by fsheremetyeva** [comment]
My plan is having interfaces for:

- The organization to manage all of the data from their perspective.

- The registered user to see local data from multiple organizations in their area and engage, etc.

- The public/default interface for any unregistered users / search bots / etc that will be able to view a similar interface to registered users but not obviously submit their information / coordinate volunteering / etc. For the most part at this point I think much of this interface will be shared with the registered user interface except for the mentioned pieces specific to registered users or account settings.

As part of the public interface would likely be a few 'informational' HTML pages just covering the concept, features, and other information for those wishing to learn more about the site.

Please let me know if I can close this issue. Thanks.
