### ISSUE TITLE
Ability to create user volunteer account

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#7]
As a new site visitor I'm able to create a volunteer account and have this information stored on the service's database.

If this is the case, this feature may require:

- [x] Volunteer Registration/Sign Up Form
  - [x] Name
  - [x] Email
  - [x] Password

- [x] Volunteer Sign In Form

**Comment by fsheremetyeva** [comment]
Create a login form, validate fields and send user's information to the database.

**Comment by brandonbrown** [comment]
Looking for clarity on this. Is this feature set to: 

As a new site visitor I'm able to create a volunteer account and have this information stored on the service's database.

If this is the case, this feature may require:

- [ ] Volunteer Registration/Sign Up Form
  - [ ] Name
  - [ ] Email
  - [ ] Password

- [ ] Volunteer Sign In Form

- [ ] Volunteer Information Profile
  - [ ] Region/Area
  - [ ] Availability
  - [ ] Interests and Unique Capabilities (Plumber, Fisher, Programming, Etc.
  - [ ] Contact Information

**Comment by fsheremetyeva** [comment]
The plan for the initial sign-up form is to provide the name/email/password for setting up the account. Then from the dashboard/profile will be the areas to set default region, interests, and contact information. At this point the user's availability isn't planned since it will be the user itself looking for volunteer opportunities as opposed to the non-profits trying to search for users.
