### ISSUE TITLE
Ability to create non-profit organization account

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#8]
As a non-profit organization we're able to join your service and organize our volunteer needs.

- [x] Organization Registration Form
  - [x] Primary Admin Contact: Email
  - [x] Organization Name
  - [x] Password
  - [x] Organization Address
  - [x] Organization Contact: Phone

**Comment by fsheremetyeva** [comment]
Create a login/registration form, validate fields and send the data to the database

**Comment by brandonbrown** [comment]
As a non-profit organization we're able to join your service and organize our volunteer needs.

If this is the feature, you may need:

- [ ] Organization Creation Form
  - [ ] Primary Admin Name
  - [ ] Primary Admin Contact: Email
  - [ ] Organization Name
  - [ ] Organization Description
  - [ ] Organization Address
  - [ ] Organization Contact: Phone

**Comment by fsheremetyeva** [comment]
Thank you for the feedback. Yes, that is what I envision.
