### ISSUE TITLE
Ability to search for volunteer opportunities

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/capstone#9]
Create the search form for the search query or zipcode.

**Comment by brandonbrown** [comment]
As a user seeking volunteer work, I can find volunteer opportunities fitting specific criteria:

- [ ] Search/filter by Region
- [ ] Search/filter by Activity
  - [ ] Physical Work
  - [ ] Informational Assistance
  - [ ] Teaching
  - [ ] Etc.
- [ ] Search/filter by Organization
- [ ] Search/filter by date

- [ ] Select result to find more details

**Comment by fsheremetyeva** [comment]
Thanks, currently evaluating what is feasible.
